from typing import Protocol, Any

class RedisService(Protocol):
    async def set_key(self, key: str, value: str, expire: int = 3600) -> None: ...
    async def get_key(self, key: str) -> Any: ...
    async def delete_key(self, key: str) -> None: ...
