"""add logentry orm

Revision ID: 2875aae92136
Revises: 943497e75d7c
Create Date: 2025-06-10 19:52:27.058755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2875aae92136'
down_revision: Union[str, None] = '943497e75d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('log_level', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid')
    )
    op.create_unique_constraint(None, 'announcements', ['uid'])
    op.create_unique_constraint(None, 'bot_documents', ['uid'])
    op.create_unique_constraint(None, 'bot_participants', ['uid'])
    op.create_unique_constraint(None, 'bot_services', ['uid'])
    op.create_unique_constraint(None, 'bots', ['uid'])
    op.create_unique_constraint(None, 'conversations', ['uid'])
    op.create_unique_constraint(None, 'messages', ['uid'])
    op.create_unique_constraint(None, 'payments', ['uid'])
    op.create_unique_constraint(None, 'platform_prices', ['uid'])
    op.create_unique_constraint(None, 'support_attachments', ['uid'])
    op.create_unique_constraint(None, 'support_items', ['uid'])
    op.create_unique_constraint(None, 'telegram_account_links', ['uid'])
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'telegram_account_links', type_='unique')
    op.drop_constraint(None, 'support_items', type_='unique')
    op.drop_constraint(None, 'support_attachments', type_='unique')
    op.drop_constraint(None, 'platform_prices', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_constraint(None, 'bots', type_='unique')
    op.drop_constraint(None, 'bot_services', type_='unique')
    op.drop_constraint(None, 'bot_participants', type_='unique')
    op.drop_constraint(None, 'bot_documents', type_='unique')
    op.drop_constraint(None, 'announcements', type_='unique')
    op.drop_table('logs')
    # ### end Alembic commands ###
