"""Update LogEntryORM init n3

Revision ID: cf5f1628c27e
Revises: f5ecc6db20d5
Create Date: 2025-06-10 21:07:46.286728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5f1628c27e'
down_revision: Union[str, None] = 'f5ecc6db20d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'log_level',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('logs', 'source',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('logs', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('logs', 'source',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('logs', 'log_level',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
