"""Update LogEntryORM init

Revision ID: fb0fcfb331bc
Revises: 2875aae92136
Create Date: 2025-06-10 20:50:54.708945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb0fcfb331bc'
down_revision: Union[str, None] = '2875aae92136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('logs', sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False))
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.drop_column('logs', 'created_at')
    op.drop_column('logs', 'updated_at')
    op.drop_column('logs', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('logs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_column('logs', 'timestamp')
    op.drop_column('logs', 'id')
    # ### end Alembic commands ###
