from typing import Protocol

class TokenBlocklistService(Protocol):
    async def block_token(self, jti: str, expiry: int) -> None: ...
    async def is_blocked(self, jti: str) -> bool: ...
    async def unblock_token(self, jti: str) -> None: ...