from typing import Protocol

class TokenService(Protocol):
    def create_access_token(self, payload: dict) -> str: ...
    def create_refresh_token(self, payload: dict) -> str: ...
    def decode_token(self, token: str) -> dict | None: ...
